#!/bin/bash

set -e

# ensure that we have the required dependencies installed
for dep in golangci-lint; do
    if ! type -t $dep > /dev/null; then
        echo "Error: '$dep' is not installed" 1>&2
        exit 1
    fi
done

# Sanity check that we have a valid bump order for all sub-modules to stop people accidentally creating dependency
# cycles.
for MOD in $(find . -name 'go.mod' | xargs dirname | grep -v 'scripts' | tr -d './'); do
    ./scripts/versioning/bump_order.py $MOD
done

# run multiple linters over the codebase before allowing allowing a push (these are the same linters that the build bot
# runs), therefore, this should mean less wasted time spent fixing mistakes picked up when it's least convenient to fix
# them.
./scripts/cv/lint.sh

# ensure that 'CHANGES.md' has been updated, run this last so that a false-positive (and use of '--no-verify') doesn't
# skip the prior checks, which are also important.
for MOD in $(find . -name 'go.mod' | xargs dirname | grep -v 'scripts' | tr -d './'); do
    if ! git diff --name-only HEAD^ | grep -q $MOD; then
        continue
    fi

    if git diff --name-only HEAD^ | grep -q 'CHANGES.md'; then
        continue
    fi

    echo "Error: It looks like you've missed updating the 'CHANGES.md' file, please confirm and use '--no-verify' if this is a false positive"

    exit 1
done
