#!/bin/bash

set -e

# ensure that we have the required dependencies installed
for dep in golangci-lint; do
    if ! type -t $dep > /dev/null; then
        echo "Error: '$dep' is not installed" 1>&2
        exit 1
    fi
done

# run multiple linters over the codebase before allowing allowing a push (these are the same linters that the build bot
# runs), therefore, this should mean less wasted time spent fixing mistakes picked up when it's least convenient to fix
# them.
golangci-lint run
