issues:
  max-issues-per-linter: 0 # Unlimited
  max-same-issues: 0 # Unlimited
linters:
  fast: false
  enable:
    - asciicheck
    - bodyclose
    - dogsled
    - godox
    - gofmt
    - gofumpt
    - goimports
    - gosimple
    - ineffassign
    - lll
    - misspell
    - nakedret
    - nestif
    - nolintlint
    - prealloc
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - unconvert
    - unparam
    - unused
    - wastedassign
    - whitespace
    - wsl
run:
  go: 1.18
linters-settings:
  lll:
    line-length: 120
  unparam:
    check-exported: true
