version: "2"
run:
  issues-exit-code: 1
  tests: true
linters:
  enable:
    - asciicheck
    - bodyclose
    - dogsled
    - godox
    - lll
    - misspell
    - nakedret
    - nestif
    - nolintlint
    - prealloc
    - revive
    - rowserrcheck
    - sqlclosecheck
    - unconvert
    - unparam
    - wastedassign
    - whitespace
    - wsl
  settings:
    lll:
      line-length: 120
    unparam:
      check-exported: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
    rules:
      # We have quite a few packages named 'util', and it's too late to change them.
      - path: ".*/util/"
        text: 'var-naming: avoid meaningless package names'
      # De Morgan's Law; ignoring because the compiler should do this anyway, and prefer readability.
      - linters: 'staticcheck'
        text: 'QF1001'
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
