issues:
  max-issues-per-linter: 0 # Unlimited
  max-same-issues: 0 # Unlimited 
linters: # TODO (MB-52626): Re-enable linters that were broken by Go 1.18.
  fast: false
  enable:
    - asciicheck
    - bodyclose
    - deadcode
    - dogsled
    - godox
    - gofmt
    - gofumpt
    - goimports
    - gosimple
    - ineffassign
    - lll
    - misspell
    - nakedret
    - nestif
    - nolintlint
    - prealloc
    - revive
    # - rowserrcheck
    # - sqlclosecheck
    - staticcheck
    # - structcheck
    - unconvert
    - unparam
    - varcheck
    # - wastedassign
    - whitespace
    - wsl
run:
  go: 1.18
linters-settings:
  lll:
    line-length: 120
  unparam:
    check-exported: true
