// Code generated by mockery v2.53.3. DO NOT EDIT.

package objgcp

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	objcli "github.com/couchbase/tools-common/cloud/v8/objstore/objcli"

	storage "cloud.google.com/go/storage"
)

// mockComposeAPI is an autogenerated mock type for the composeAPI type
type mockComposeAPI struct {
	mock.Mock
}

// Run provides a mock function with given fields: ctx
func (_m *mockComposeAPI) Run(ctx context.Context) (*storage.ObjectAttrs, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 *storage.ObjectAttrs
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*storage.ObjectAttrs, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *storage.ObjectAttrs); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*storage.ObjectAttrs)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SetLock provides a mock function with given fields: lock
func (_m *mockComposeAPI) SetLock(lock *objcli.ObjectLock) error {
	ret := _m.Called(lock)

	if len(ret) == 0 {
		panic("no return value specified for SetLock")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*objcli.ObjectLock) error); ok {
		r0 = rf(lock)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// newMockComposeAPI creates a new instance of mockComposeAPI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockComposeAPI(t interface {
	mock.TestingT
	Cleanup(func())
},
) *mockComposeAPI {
	mock := &mockComposeAPI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
