// Code generated by mockery v2.9.4. DO NOT EDIT.

package objgcp

import mock "github.com/stretchr/testify/mock"

// mockServiceAPI is an autogenerated mock type for the serviceAPI type
type mockServiceAPI struct {
	mock.Mock
}

// Bucket provides a mock function with given fields: name
func (_m *mockServiceAPI) Bucket(name string) bucketAPI {
	ret := _m.Called(name)

	var r0 bucketAPI
	if rf, ok := ret.Get(0).(func(string) bucketAPI); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(bucketAPI)
		}
	}

	return r0
}
