// Code generated by mockery v2.28.2. DO NOT EDIT.

package objgcp

import (
	storage "cloud.google.com/go/storage"
	mock "github.com/stretchr/testify/mock"
)

// mockReaderAPI is an autogenerated mock type for the readerAPI type
type mockReaderAPI struct {
	mock.Mock
}

// Attrs provides a mock function with given fields:
func (_m *mockReaderAPI) Attrs() storage.ReaderObjectAttrs {
	ret := _m.Called()

	var r0 storage.ReaderObjectAttrs
	if rf, ok := ret.Get(0).(func() storage.ReaderObjectAttrs); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(storage.ReaderObjectAttrs)
	}

	return r0
}

// Close provides a mock function with given fields:
func (_m *mockReaderAPI) Close() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Read provides a mock function with given fields: p
func (_m *mockReaderAPI) Read(p []byte) (int, error) {
	ret := _m.Called(p)

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func([]byte) (int, error)); ok {
		return rf(p)
	}
	if rf, ok := ret.Get(0).(func([]byte) int); ok {
		r0 = rf(p)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = rf(p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTnewMockReaderAPI interface {
	mock.TestingT
	Cleanup(func())
}

// newMockReaderAPI creates a new instance of mockReaderAPI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func newMockReaderAPI(t mockConstructorTestingTnewMockReaderAPI) *mockReaderAPI {
	mock := &mockReaderAPI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
