// Code generated by mockery v2.9.4. DO NOT EDIT.

package objazure

import mock "github.com/stretchr/testify/mock"

// mockBlobStorageAPI is an autogenerated mock type for the blobStorageAPI type
type mockBlobStorageAPI struct {
	mock.Mock
}

// ToContainerAPI provides a mock function with given fields: container
func (_m *mockBlobStorageAPI) ToContainerAPI(container string) containerAPI {
	ret := _m.Called(container)

	var r0 containerAPI
	if rf, ok := ret.Get(0).(func(string) containerAPI); ok {
		r0 = rf(container)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(containerAPI)
		}
	}

	return r0
}
